# Adjust the custom JavaScript to ensure that only code cells are togglable, while markdown cells remain always visible.

# Use default HTML exporter to get a clean start
exporter = HTMLExporter()
body, resources = exporter.from_notebook_node(nb)

# Update custom JavaScript to target only code cells for toggling
custom_js_updated = """
<script>
document.querySelectorAll('.jp-CodeCell').forEach((cell) => {
    const button = document.createElement('button');
    button.textContent = 'Show Code';
    button.style = 'margin-bottom: 5px;';
    const codeArea = cell.querySelector('.jp-InputArea');
    button.onclick = function () {
        if (codeArea.style.display === 'none') {
            codeArea.style.display = 'block';
            this.textContent = 'Hide Code';
        } else {
            codeArea.style.display = 'none';
            this.textContent = 'Show Code';
        }
    };
    cell.insertBefore(button, cell.firstChild);
    codeArea.style.display = 'none'; // Initially hide code cells
});
</script>
"""

# Append the updated custom JS to the end of the body
body += custom_js_updated

# Save the modified HTML with updated JS ensuring markdown cells are always visible
output_html_path_custom_js_updated = '/mnt/data/01_scCellFie_Metabolism_custom_js_updated.html'
with open(output_html_path_custom_js_updated, 'w', encoding='utf-8') as f:
    f.write(body)

output_html_path_custom_js_updated


## untested code generated by chatgpt
## toggles code cells off
